### ISSUE TITLE
Get rid of `!` in `Camera` functions

### ISSUE THREAD

**Issue by ehgus** [IHPSystems/Cameras.jl#8]
Some `Camera` functions have an argument modification sign `!` but it does not look like it modifies arguments.

I guess you appended the sign because such functions change I/O state of a camera connected.
I think it does not count in the case of "changing arguments", as you can see in [an example of VideoIO.jl](https://juliaio.github.io/VideoIO.jl/stable/reading/#Reading-Camera-Output).

If my guess is correct, can you consider removing the `!` sign from the `Camera` functions?

**Comment by stemann** [comment]
All `Cameras` functions with `!` in their name mutate their first argument, the camera state - the behaviour of subsequent calls depend on the mutating calls:
* `open!`: Camera should change state to being open.
* `close!`: Camera should change state to being closed.
* `start!`: Camera should change state to being started.
* `stop!`: Camera should change state to being stopped.
* `take!`: Camera changes states to have taken one additional image - e.g. image count/id could be incremented.
* `trigger!`: Camera is triggered - also a state change - a subsequent `take!` call return rather than block.

`take!` mirrors take! (and `put!`) on a Base `Channel`.

**Comment by stemann** [comment]
I think https://juliaio.github.io/VideoIO.jl/stable/reading/#Reading-Camera-Output is wrong.

**Comment by stemann** [comment]
I also think `Base` might be wrong to have `close(stream)` and `close(::Channel)` rather than `close!(stream)` and `close!(::Channel)`.

**Comment by stemann** [comment]
> I also think `Base` might be wrong to have `close(stream)` and `close(::Channel)` rather than `close!(stream)` and `close!(::Channel)`.

Similar discussion: https://discourse.julialang.org/t/why-is-it-close-channel-instead-of-close-channel/24261/3

**Comment by ehgus** [comment]
> Similar discussion: https://discourse.julialang.org/t/why-is-it-close-channel-instead-of-close-channel/24261/3

The discussion points out whether the inherent change should be counted in argument modification, and the same problem arises in [PcoCamera](https://github.com/ehgus/PcoCameras.jl).

After reading it, I realized that distinguishing inherent changes and explicit changes could confuse users.
Maybe it is best to keep `!` in the functions for clarity.
